version: '3.7'

services:
  db:
    restart: always
    image: postgres:13
    container_name: db_app
    environment:
      POSTGRES_DB: "fastapi_eshop"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "223344"
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data/



  app:
    build: 
      context: .
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

networks:
  backend:
     driver: bridge

volumes:
  pg_data: null