version: '3.7'

services:
  db:
    restart: always
    image: postgres:13
    container_name: db_app
    env_file:
      - .env-prod
    ports:
      - "5432:5432"
    networks:
      - backend


    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  app:
    build: 
      context: .
    command: ["/fastapi_app/docker/app.sh"]
    env_file:
      - .env-prod
    ports:
      - 9999:8000
    networks:
      - backend
    depends_on:
      - "db"

networks:
  backend:
     driver: bridge

volumes:
    dump: