version: '3.7'

services:
  db:
    restart: always
    image: postgres:13
    container_name: db_app
    env_file:
      - .env-prod
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - data:/var/lib/postgresql/data

  app:
    build: 
      context: .
    command: ["/fastapi_app/docker/app.sh"]
    env_file:
      - .env-prod
    ports:
      - 9999:8000
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

networks:
  backend:
     driver: bridge

volumes:
    dump:
    data: