"""fourth

Revision ID: 05b859e0eb12
Revises: faade46b4e45
Create Date: 2023-11-17 15:31:55.203403

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '05b859e0eb12'
down_revision = 'faade46b4e45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('accessory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accessory_id'], ['Accessories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['Vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('accessory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accessory_id'], ['Accessories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['Vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Users', sa.Column('cart', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Users', 'Cart', ['cart'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'cart')
    op.drop_table('Orders')
    op.drop_table('Cart')
    # ### end Alembic commands ###
