"""second

Revision ID: 10d5d71cd153
Revises: 9134c20fb1ac
Create Date: 2023-05-17 17:21:52.614793

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '10d5d71cd153'
down_revision = '9134c20fb1ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Accessories', sa.Column('product_code', sa.Integer(), nullable=True))
    op.add_column('Accessories', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('Vehicles', sa.Column('product_code', sa.Integer(), nullable=True))
    op.add_column('Vehicles', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Vehicles', 'rating')
    op.drop_column('Vehicles', 'product_code')
    op.drop_column('Accessories', 'rating')
    op.drop_column('Accessories', 'product_code')
    # ### end Alembic commands ###
