"""First

Revision ID: 9134c20fb1ac
Revises: 
Create Date: 2023-05-14 15:26:29.786023

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9134c20fb1ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('engine', sa.Integer(), nullable=True),
    sa.Column('engine_type', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('amount_in_stock', sa.Integer(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Quads')
    op.drop_table('Boats')
    op.drop_table('Jet_ski')
    op.drop_table('Engines')
    op.drop_table('ATVs')
    op.drop_table('Snowmobiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Snowmobiles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Snowmobiles_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_in_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Snowmobiles_pkey')
    )
    op.create_table('ATVs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ATVs_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_in_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ATVs_pkey')
    )
    op.create_table('Engines',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Engines_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_in_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Engines_pkey')
    )
    op.create_table('Jet_ski',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Jet_ski_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_in_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Jet_ski_pkey')
    )
    op.create_table('Boats',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Boats_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_in_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Boats_pkey')
    )
    op.create_table('Quads',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Quads_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_in_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Quads_pkey')
    )
    op.drop_table('Vehicles')
    # ### end Alembic commands ###
