"""third

Revision ID: faade46b4e45
Revises: 06b9c742b015
Create Date: 2023-11-16 15:00:24.514628

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'faade46b4e45'
down_revision = '06b9c742b015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registered_at', sa.Date(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Accessories', sa.Column('material', sa.String(), nullable=True))
    op.add_column('Accessories', sa.Column('guarantee', sa.Integer(), nullable=True))
    op.add_column('Accessories', sa.Column('color', sa.String(), nullable=True))
    op.add_column('Accessories', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Accessories', 'company')
    op.drop_column('Accessories', 'color')
    op.drop_column('Accessories', 'guarantee')
    op.drop_column('Accessories', 'material')
    op.drop_table('Users')
    # ### end Alembic commands ###
